name: Build

on:
  push:
    branches:
      - main
      - dev


jobs:
  build:
    name: Build and analyze
    runs-on: windows-latest
    
    steps:
      - name: Checkout SharpSDL3
        uses: actions/checkout@v4
        with:
          repository: Blizzardo1/SharpSDL3
          path: SharpSDL3
      - name: Build and analyze
        shell: powershell
        run: |
          dotnet build TestGame/TestGame.csproj
